name: Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is. How to reproduce it?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of Expresii are you using?
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Reproducibility
      options:
        - label: I have verified this bug exists on the latest version.
          required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of Expresii are you using?
    validations:
      required: true
  - type: textarea
    id: systeminfo
    attributes:
      label: System Information
      placeholder: Please provide information of your OS, GPU, GPU driver version. Tip: you can copy and paste the system information from the "System Info" dialog of Expresii here.
    validations:
      required: false    
      